import type { ChurchId } from "@/content/churches";

export type SocietySection = {
  title: string;
  paragraphs: string[];
};

export type SocietyPicture = {
  src: string;
  kind: "society" | "artefact";
};

export const churchSocietyPictures: Partial<Record<ChurchId, SocietyPicture[]>> = {
  ephesus: [
    { src: "/images/churches/ephesus/01-columns-ruin.jpg", kind: "society" },
    { src: "/images/churches/ephesus/02-artemis-statue.webp", kind: "artefact" },
    { src: "/images/churches/ephesus/03-agora.jpg", kind: "society" },
    { src: "/images/churches/ephesus/04-vaulted-arcade.jpg", kind: "society" },
    { src: "/images/churches/ephesus/05-artemis-statue.jpg", kind: "artefact" },
    { src: "/images/churches/ephesus/06-artemis-huntress.jpg", kind: "artefact" },
    { src: "/images/churches/ephesus/07-arcade-fountain.jpg", kind: "society" },
    { src: "/images/churches/ephesus/08-city-harbour.webp", kind: "society" },
    { src: "/images/churches/ephesus/09-temple-model.jpg", kind: "society" },
  ],
};

export const churchSocieties: Partial<Record<ChurchId, SocietySection[]>> = {
  ephesus: [
    {
      title: "Society of Ephesus",
      paragraphs: [
        "Ephesus was the most important city in western Asia Minor (modern Turkey) in New Testament times. In fact, it was called “the mother city” of Asia. It had an estimated population of around 200,000–250,000.",
        "Its wealth and importance came from its location. It was situated on an inland harbour linked by a canal to the River Cayster which flowed into the Aegean Sea; and it was at the crossroads of major trade routes. So it was an extremely important commercial centre — in fact, the largest trading centre in Asia Minor.",
        "The city had gymnasiums, theatres (one of them seating 25,000), a triumphal arch and a fabulous library (though this was only built after New Testament times). It had won the right to house the temple of the divine Julius (Caesar) and the Goddess Roma, and had a huge temple to the emperor Domitian (AD 81–96).",
        "The city’s greatest claim to fame didn’t lie in the realm of business or economics, but religion.",
        "The most important structure in Ephesus was a major temple to the Greek goddess Artemis (known in Rome as Diana), which was one of the 7 wonders of the ancient world and which people came from far and wide to see. It was 425 feet (130m) long and 220 feet (67m) wide, with white marble columns 62 feet (19m) high and just 4 feet (1.2m) apart. The temple was founded when her image — probably a meteorite — “fell from heaven” (Acts 19:35).",
        "Ephesus became known as “the guardian of the temple of the great Artemis and her image which fell from heaven.” It was a sacred site for over 1200 years.",
      ],
    },
    {
      title: "Artemis",
      paragraphs: [
        "In Greek and Roman mythology Artemis was the daughter of Zeus and the twin sister of Apollo. She was the goddess of the hunt and wild animals, as well as the goddess of women. She protected women in childbirth, protected young girls, especially their virginity, and brought relief to women in need.",
        "A eunuch priest served Artemis, assisted by virgin priestesses. This heavily-women-dominated religion may be part of the reason why Paul insists so much on women keeping their proper place in the church, and on men rising up to play their proper role in worship (1 Timothy 2:8–15). (Remember that, by the time Paul wrote to Timothy, Timothy was leading the church in Ephesus).",
        "As a fertility goddess, ritual prostitution played an important part in the worship of Artemis. So, from a Christian point of view, the temple was an exceedingly immoral. Worship also included many secret rituals or “mysteries”, portraying birth and death — hence Paul’s repeated use of the word “mystery” in his letter (Ephesians 1:9; 3:3, 4, 6, 9; 5:32; 6:19). The difference was that whereas their “mystery” was hidden and secret, revealed only to the special few, Paul says that God’s “mystery” has now been made fully known in Jesus — to everyone!",
        "But the temple wasn’t just about religion; it was also about business — big business! There was a guild of silversmiths who made little silver shrines and copies of the stone that fell from heaven.",
        "Her temple served as the city’s main bank, and thousands of temple servants were entrusted with looking after the fortunes that people entrusted to them. Artemis’ image was also on their coins, and festivals and games held in her honour. So to challenge Artemis, like Paul did, was to challenge the whole social and economic order. But that is what the gospel is meant to do!",
      ],
    },
  ],
  smyrna: [
    {
      title: "Society of Smyrna",
      paragraphs: [
        "Smyrna was an ancient city on a small peninsula jutting out from Asia Minor into the Aegean Sea. It was originally established around 1000 BC by Aeolian Greek settlers in “Old Smyrna.” The famous Greek poet Homer, author of the epics the Iliad and the Odyssey, was probably born around 850 BC, and a shrine to Homer stood in the Roman period.",
        "After the time of Alexander the Great in the late 4th century BC, a “new” Smyrna was built by the Seleucids along the coast and up the slopes of Mount Pagos. This region eventually became part of Asia Province during the Roman period, and Smyrna, between Ephesus and Pergamum, developed into a wealthy port city and one of the most important cities of the province, with a population of nearly 100,000 residents.",
        "During the Roman period, Smyrna was apparently a city of great beauty and impressive architecture that circled Mount Pagus like a “crown.” Walking through the city, one would see the Ephesian gate, a gymnasium near the harbor, a stadium on the west side, and a theater holding 20,000 on the northwest mountain slope. There were temples to Zeus (including a large altar), Cybele the Mother Goddess near the harbor, Aphrodite, Dionysius, and the Emperors — probably Tiberius in AD 26 and Domitian before AD 96 — as well as the harbor, a library, and a massive agora with a bema on the west and a basilica on the north.",
        "Smyrna was severely damaged by an earthquake in AD 178. The Roman-period city was repaired or rebuilt in the 2nd century AD. This wealthy city was also known for its exceptionally good wine, used for both enjoyment and medicinal purposes.",
        "Like Ephesus, Smyrna competed for the title of “first of Asia” as well as for the right to build a temple for Tiberius. Because of its history with Rome, Smyrna was awarded the right, and later was awarded it again by Hadrian. Not only was it a city beloved by Rome for its patriotism, but it was also beloved by the people for its beauty. The design of the city itself was lauded, but of particular beauty was the “crown of Smyrna,” a street that encircled the top of Mt. Pagos.",
        "Smyrna chose for itself the patron goddess Cybele, and depicted her on its currency as seated on a throne wearing a crown. Also lauded in Smyrna were its wines, its wealth, and its love of science and medicine.",
        "While Smyrna was a jewel among the cities of Rome, there is a stark contrast between the love of itself and its rejection of Christians. Perhaps not at first, but over time the Roman empire came to despise and persecute the church there. The Smyrna we find in the first and second centuries AD was one where Christians were less and less welcome. They were excluded from jobs they needed and they suffered economically for it. Eventually Christians in Smyrna were even imprisoned or put to death, as was the case with Polycarp (AD 155–165).",
      ],
    },
  ],
  pergamos: [
    {
      title: "Society of Pergamos",
      paragraphs: [
        "Pergamon came into its own after Alexander the Great died in 323 B.C. and his brief empire was carved among his generals. Lysimachus inherited the settlement and its treasure. Set on land and sea routes, and enriched by the Attalid kings who ruled from 282 to 133 B.C., the city prospered for centuries. In 133 B.C. it passed peacefully into Rome’s hands. From that hour Pergamon’s fortune rose and fell with the empire itself.",
        "The acropolis still stands in triumph above the wreck of the city, which spills down the steep slopes into the valley. On that same face the nearly intact theater hangs toward the sea — one of the steepest in the ancient world, and among the most spectacular. Ten thousand spectators once picked their way down eighty rows of seating, dizzy against the drop.",
        "Scholars identify the most dramatic ruin on the southern slope as the Temple of Zeus. Only its massive foundations remain. The altar that belonged to it, known now as the Great Altar of Pergamon, once occupied a sacred precinct on the acropolis: a monumental Π-shaped hall of columns, reached by a grand staircase. Around its whole exterior ran a marble frieze 113 meters long and 2.3 meters high — the gigantomachy, the war of the Olympian gods against the Giants. Myth said the giants could be defeated only with the help of a mortal. Zeus, with Athena at his side, called Herakles, whose arrows struck the decisive blow. Later art crowded the scene with other Greek heroes. In the nineteenth century German archaeologists carried the altar to Berlin. The Ottoman authorities, indifferent, gave them little trouble.",
        "North of Zeus and the altar stand the remains of the Temple of Athena, raised at the end of the fourth century or the opening of the third, and dedicated to the city’s patron goddess. Northwest of it stood the famous library. The figure of 200,000 papyrus and parchment volumes is probably too high — Seneca put some 40,000 in the greater library at Alexandria — yet Pergamon’s collection was still among the largest in the ancient world, and its name traveled the Mediterranean.",
        "Below, at a sacred spring, the Asklepion served the god Asklepius “Soter” — savior. Founded in the fourth century B.C. and modeled on the shrine at Epidaurus, it was at once a temple of healing and a kind of magical hospital. The ruins visible now belong chiefly to the second-century A.D. rebuild after an earthquake, but the first-century complex was essentially the same. In the Roman world medicine, magic, and the gods were rarely kept apart. Galen, the celebrated physician of second-century Pergamum, worked with this Asklepion. A physician need not bow to pagan religion: Luke, the Christian, is the counter-example (Colossians 4:14).",
        "Those who came for healing entered, were ritually cleansed, offered sacrifice, drank a potion, and descended into the “abaton” — the “inaccessible place,” thought to touch the underworld. There, in a room of snakes, they slept and waited for a dream from Asklepius. This was incubation, dream therapy. On waking they told the dream to a priest, who interpreted it and prescribed a cure. The healed left an offering in the shape of the body part restored. Myth even claimed that Asklepius could raise the dead.",
        "The serpent was his sign, and not his alone. Ancient stories said Alexander the Great and Caesar Augustus were conceived by a god in snake form. Dionysus, who had a temple on the acropolis, was likewise bound to a sacred snake. First-century B.C. coins of Pergamum show the “cista mystica,” the box borne in his processions, a serpent inside it as the god himself.",
        "Serapis, housed in the lower city, seldom wore serpent imagery, yet he too belonged to the underworld — an Egyptian-Hellenistic blending of Osiris, Hades, and Pluto. In the fourth century a Byzantine church rose on the Red Court over his temple. Its dedication is unknown. It may have honored Antipas, bishop of Pergamum, murdered for his faith in Christ in the late first century (Revelation 2:13). No other early source tells how or where he died. The later legends may be conjecture.",
        "Pergamum was also a seat of the imperial cult. Caesar Augustus made it “neokoros,” temple warden — the first city in all Asia Minor to build an imperial temple and host the worship of the emperor. Trajan’s temple still marks the acropolis; Augustus’s appears on the city’s coins. Trajan may have taken that earlier house for himself.",
        "When Revelation speaks of Pergamum as the place of “Satan’s throne” and “where Satan dwells,” the phrases have been read in several ways, all of them pagan (Revelation 2:13). Most often the throne is the Great Altar itself, throne-shaped, and bound to Zeus, who overthrew the Titans — a myth that shadows Satan’s bid to unseat God (Isaiah 14:12–14; Ezekiel 28:14–16; Revelation 12:7–9). Others point to emperor worship, and to the city as the imperial cult’s heart in Asia Minor. The Asklepion has been proposed, and the temple of Dionysus. But those gods had temples in many first-century cities. The “throne” and the dwelling may name the whole of Pergamum: a center of satanic worship, written in the density of its paganism.",
        "Some in the church were rebuked for the teaching of Balaam, for sacrifices to idols, and for immorality — all of it bound to that pagan world (Revelation 2:14). The verb usually rendered “to eat things sacrificed to idols” may mean “memorial meals for the dead,” a common Hellenistic and Roman rite. The “immorality” may be spiritual harlotry: the worship of false gods beside, or instead of, Jesus Christ. In either reading, some Christians at Pergamum had entered pagan ritual. The Nicolaitans taught such things. To those who overcome, the letter promises a new name written on a white stone — a lasting mark, set against the parchment for which the city was so famous, and which does not last (Revelation 2:17).",
        "In the third century A.D. an earthquake tore the city, and Gauls sacked what remained. After that, little of consequence was built. The Hellenistic and Roman ruins survived because the later city did not cover them.",
      ],
    },
  ],
  thyatira: [
    {
      title: "Society of Thyatira",
      paragraphs: [
        "Leaving Pergamos, the Roman imperial road led to Thyatira, the city whose church received the fourth of the seven letters of Revelation.",
        "Thyatira was founded about 300 B.C. by Seleucus I, Alexander’s general. In Roman times its chief deity was Apollo, the sun god. Zeus, Artemis, Demeter, and Athena were also worshiped there, and a coin of Vespasian suggests that a temple to the Emperor may have stood in the city by at least A.D. 79.",
        "The city appears in Acts and Revelation as the hometown of Lydia, and later as one of the chief churches of Asia Minor (Acts 16:14; Revelation 2:18–29). Lydia, Paul’s first European convert at Philippi, had come from Thyatira. Paul himself may have brought the Gospel there during the three years he spent in the Province of Asia, most of that time in Ephesus (Acts 19:10; 20:31).",
        "Inscriptions show a city of trade guilds: wool, linen, baking, slaves, leather, bronze, pottery, and dyes. One of its great industries was the dyeing of textiles. The purple of Thyatira was not the rare murex of the Mediterranean coast, but a cheaper “imitation” drawn from the madder root — easier to get, cheaper to make, and sold in volume. In modern times that dye is called “Turkey Red.” Its low cost and the scale of its production made the trade very profitable.",
        "Lydia, who had moved from Thyatira to Philippi in Macedonia, worked in that trade as a seller of purple-dyed fabrics (Acts 16:14). An inscription at Philippi honors a purple-dye dealer from Thyatira who was patron to a citizen there. Others in the dye business, like Lydia, had made the same journey, and they were people of means.",
        "Coins and inscriptions also show smiths, especially workers in bronze. Some of the city’s coins depict Hephaestus, blacksmith of the gods, with hammer and tongs at a helmet. Others show Demeter holding a fiery torch. The letter’s images of fire, fine bronze, a rod of iron, and broken pottery may be word pictures drawn from trades every Thyatiran knew (Revelation 2:18, 27).",
        "First-century Thyatira was a pagan city, like many others in the Roman Empire. The letter to its church, however, names a particular danger: a false, self-proclaimed prophetess whom John calls “Jezebel,” after the pagan Phoenician queen of Israel, associated with harlotry and witchcraft (Revelation 2:20; 1 Kings 16:31; 2 Kings 9:22).",
        "The “deep things of Satan” may point to the mystery religions — rites kept secret, opened only to initiates (Revelation 2:24). Demeter, one of the main goddesses of Thyatira, stood at the heart of the ancient Eleusinian Mysteries.",
        "Thyatira also had a community of Jews. Some of them may have syncretized with paganism, as Israel did in the days of Jezebel. It is more likely that the letter uses the name as an illustration of the evil the prophetess was teaching inside the church.",
        "Today the town’s central square holds a monument to Kemal Ataturk, Turkey’s national hero. The visitor searches in vain for anything that still speaks of the ancient city.",
      ],
    },
  ],
  sardis: [
    {
      title: "Society of Sardis",
      paragraphs: [
        "Sardis was the capital of the flourishing kingdom of Lydia and one of the great cities of ancient Anatolia. Strategically located on a spur at the foot of Mount Tmolus (Boz Dağ), the city commanded the central plain of the Hermus Valley and stood at the western terminus of the Persian Royal Road. Below it stretched the well-watered plain of the Hermus River (modern Gediz Irmak) and the Gygaean Lake (modern Marmara Gölü), while above the plain its acropolis rose in sheer, undulating cliffs to a height of about 300 meters. This dramatic natural setting formed an almost invulnerable citadel.",
        "The land surrounding Sardis also provided the city with considerable natural wealth. The fertile plain was dotted with small villages and estates, some belonging to wealthy landowners who, especially during the Persian period, were buried in conspicuous tumuli containing spectacular burial offerings. Behind the city, the Tmolus Mountains provided further resources. By the Hellenistic period, parts of their rich forests had become royal preserves, while marble was extracted from quarries located throughout the mountain range.",
        "Against this prosperous geographical setting, Sardis flourished as the capital of the Lydian kingdom during the 7th century B.C.E. It became the first city where gold and silver coins were minted, and from about 560 to 546 B.C.E. it was ruled by Croesus, the last king of Lydia, whose enormous wealth became famous.",
        "Lydian rule ended when Sardis was taken by the Persians around 546 B.C.E. Over the centuries that followed, the city fell in turn to the Athenians, the Seleucids, and the Attalids before being bequeathed to the Romans in 133 B.C.E. Under the Roman Empire, Sardis became the metropolitan capital and center of judicial administration of the Roman province of Lydia. Although an earthquake destroyed the city in A.D. 17, it was rebuilt and remained one of the great cities of Anatolia until the later Byzantine period. Its long history as a major city finally came to an end in 1402, when it was obliterated by the Turkic conqueror Timur, also known as Tamerlane.",
        "One of the features for which ancient Sardis became particularly famous was its seemingly impregnable citadel. Modern writers regularly describe it, while citing the historian Polybius, as “the strongest place in the world.” The statement, however, takes on a different meaning when read in its original context. Polybius (c. 200 to c. 118 B.C.E.) was describing the capture of Achaeus (d. 213 B.C.E.), lord of Sardis, by Antiochus III, known as Antiochus the Great (r. 223–187 B.C.E.). Achaeus had been secretly tricked into leaving the citadel and was captured. His people, knowing nothing of his abduction, continued to believe that he was safely protected inside “the strongest place in the world” (8.20.12). Polybius’ statement is therefore ironic; he was not actually declaring that the citadel of Sardis was the strongest place in the world.",
        "The wealth and importance of Sardis were also expressed through its religious life, most dramatically in the enormous Temple of Artemis. Situated against the backdrop of the Tmolus Mountains, the Temple of Artemis stands as the fourth largest Ionic temple in the ancient world. Like the Anatolian temples dedicated to Artemis at Ephesus and Magnesia, the structure faces west. Although an early sanctuary had existed at the site since at least the Persian period, construction of the great temple visible today began during the Hellenistic period, in the 3rd century B.C. At first, only the main building, or cella, was completed. The temple continued to evolve over the centuries, receiving later additions and alterations during the Roman period.",
        "The structure followed the peripteros plan, a Greek or Roman temple design in which the building is surrounded by a portico of columns. Constructed from marble, it featured rounded and embroidered column bases standing on square pedestals, fluted column shafts, and intricately carved Ionic column heads. Its distinctive pseudodipteral design placed eight columns across the front and back and twenty along the sides, producing an enormous structure measuring 44.58 by 97.60 meters. Inside was a large central nave accompanied by smaller chambers dedicated to religious purposes associated with Artemis, the goddess of hunting, fertility, and soil. Yet the temple was connected not only with the religious life of Sardis but also with the city’s economic activity. Sardis traded in gold and silver, and the temple became a hub for these industries. Its large treasury attracted merchants and traders.",
        "The worship of Artemis at Sardis had deep roots, and the Sardian cult appears to have had its Archaic origins in Ephesus. Around 560 B.C., Croesus famously dedicated several columns in the Temple of Artemis at Ephesus. These columns were distinguished by sculpted reliefs on tall, cylindrical pedestals. Lydian inscriptions from Sardis also contain numerous references to the Ephesian Artemis. There is even mention of a golden figure of Artemis being brought from Ephesus to Sardis for a feast celebration, although this appears to refer to an unknown sanctuary of Artemis located on the Gygean Lake, or Lake Coloë. It is therefore possible that the temple at Sardis was a branch of the Ephesian cult of the Mother Church of Artemis Ephesia. Nevertheless, Artemis at Ephesus and Artemis at Sardis unquestionably represented different aspects of the same goddess and different modes of worship.",
        "The Sardian cult of Artemis remained the primary religious belief associated with the sanctuary. At the same time, the sacred ground accommodated a variety of ancestral beliefs. Particularly important were the overlapping cults of the goddesses Cybele/Kybebe and Artemis, whose identities were subtly protean, inclusive, and changing.",
        "The religious function of the great temple itself also changed with the political world around it. During Roman times, the building was divided into two equal chambers, with one half dedicated to the imperial cult. Colossal statues of Roman emperors discovered inside the building provide evidence of this transformation. Even after Sardis was awarded its second neokorate in the second century A.D. and the great temple came to be shared with the Roman imperial cult, the Sardian cult of Artemis continued. The sanctuary therefore remained sacred ground in which older ancestral beliefs, the worship of Artemis, the overlapping traditions associated with Cybele/Kybebe, and the newer religious demands of the Roman imperial cult existed within the changing religious life of Sardis.",
      ],
    },
  ],
  philadelphia: [
    {
      title: "Society of Philadelphia",
      paragraphs: [
        "Philadelphia was founded by the King of Pergamum in the 2nd century B.C.E. and was named for the king’s brother Attalus, whose loyalty had earned him the nickname Attalus Philadelphos, literally meaning “one who loves his brother.”",
        "By the first century A.D., Philadelphia was under Roman rule and occupied a strategically important position. The city stood on a major trade route connecting Rome with significant cities in Turkey and continuing eastward. Situated on a low hill, Philadelphia also lay on a frontier of cultures. It served as a gateway into central Asia Minor, where patterns of life were neither Greek nor Roman. This strategic position has been connected with the “open door” mentioned in Revelation 3:7–8. For the early community of Christian believers, Philadelphia’s location provided an open door through which the Good News could be shared.",
        "Philadelphia was also a city familiar with instability. After receiving Roman relief following the earthquake of A.D. 17, the city sought, in gratitude, to change its name to Neocaesarea. Although the new name was short-lived, this episode has also been connected with an allusion in the apocalyptic letter to Philadelphia (Revelation 3:12). The city’s history of earthquakes may likewise lie behind the promise that the faithful believer would be made a pillar in the temple (Revelation 3:12). For people accustomed to buildings shaking and falling, the image of a permanent pillar would have carried particular significance. Permanency would have been important to the residents of Philadelphia.",
        "During the Roman period, the city experienced significant growth and development. Following the spread of Christianity around A.D. 40, Philadelphia emerged as an important center where Paul’s disciples could gather. In Paul’s time, the Philadelphia Church was founded.",
        "Although several ancient cities bore the name Philadelphia, this is definitely the Philadelphia listed by John among the seven churches of Asia in the Book of Revelation. Philadelphia is the sixth of the seven churches (Revelation 1:11), and a letter specifically addressed to the Philadelphian church is recorded in Revelation 3:7–13.",
        "The letter reveals that the Christians of Philadelphia were suffering persecution at the hands of the local Jews, whom Revelation calls “the synagogue of Satan” (Revelation 3:9). The presence of an active Jewish synagogue in Philadelphia is also mentioned by Ignatius in a letter to the church. Bitterly nationalistic, the Jews of Philadelphia fought the Christian secessionists with every refinement of persecution. In his apocalyptic letter, the author insisted that the true Jew was instead one who correctly understood his international privilege and responsibility.",
        "Against this setting, the imagery used in the letter to Philadelphia becomes closely connected with the circumstances of the city. Its strategic position as a gateway to central Asia Minor provides the setting for the “open door” of Revelation 3:7–8; the presence of an active synagogue helps explain the conflict reflected in the letter; and a population familiar with devastating earthquakes could readily understand the significance of the promise of becoming a permanent pillar.",
        "Philadelphia shares with Smyrna the distinction of receiving nothing but praise from Christ. This explains why modern Protestant churches sometimes use “Philadelphia” as a component of the local church’s name as a way of emphasizing its faithfulness.",
        "The city itself would eventually acquire an extraordinary reputation for Christian endurance. Three centuries after the first-century Christian community, paganism would take hold and Philadelphia would become known as “Little Athens” because of its dedication to foreign deities. Yet Philadelphia also maintained a long and valiant Christian history.",
        "In the 14th century, when the Eastern Roman Empire had been driven out of Asia Minor by the advancing Muslims, except for a small bridgehead opposite Constantinople, Philadelphia continued to resist. Surrounded by Turkish-controlled territory, it remained an island of Christian civilization in the Turkish sea. Gibbon paid eloquent tribute to this remarkable endurance through his reference to the standing pillar.",
      ],
    },
  ],
  laodicea: [
    {
      title: "Society of Laodicea",
      paragraphs: [
        "The city of Laodicea (Greek Laodikeia), commonly distinguished as Laodicea ad Lycum, was situated about one mile south of the Lycus River in the Lycus Valley, west of Colossae and south of Hierapolis. The city was established and fortified around 261 B.C. by the Seleucids under Antiochus II Theos.",
        "The settlement had previously been known as Rhoas and later as Diospolis, meaning “city of Zeus.” After the Seleucids gained control of the city, Antiochus II renamed it Laodicea after his wife, Queen Laodice I, an Anatolian noblewoman. Laodice I became a powerful and ruthless queen who was instrumental in the assassination of her rivals and in the events that initiated the Third Syrian War, also known as the Laodicean War. The earlier names of the city are recorded by Pliny in his Natural History.",
        "Following Roman annexation, the relocation of the principal trade route through Asia Minor placed Laodicea at a major crossroads. This contributed to its development into one of the wealthiest cities in the region by the first century B.C. The exchange of goods, banking, the profitable black-wool trade, an innovative medical school, and a shrine to the god Men all contributed to its prosperity. During the Roman period, Laodicea became one of the most prominent cities in the Province of Asia and was designated a free city, giving it a measure of independence similar to that of the Decapolis.",
        "Laodicea was built on a plateau between the smaller rivers of Asopus to the west and Caprus to the east. The city also benefited from the agricultural potential of the surrounding region and from locally available marble. The Province of Asia was wealthier and more influential than many other regions of the Roman Empire, and Laodicea shared in this prosperity.",
        "Education was a significant value to the city, producing notable philosophers during the first centuries B.C. and A.D., including Aenesidemus, Antiochus of Laodicea, and Theiodas of Laodicea. These philosophers wrote and taught in the city, were associated with the school of Pyrrhonism, and were known as sceptics.",
        "During the first century, coins used by the inhabitants carried the name of Laodicea and the names of certain magistrates. They also depicted numerous pagan gods and goddesses, including Apollo, Isis, Zeus, Athena, Men, Asklepios, Dionysus, and Aphrodite. The coinage reflected both the prominent free status of the city and the importance of pagan deities within Laodicean society.",
        "Among the more distinctive features of Laodicea during the Roman period were its famous medical school, its textile industry, and its complex water system. All three provide historical background to language used in the letter to Laodicea in Revelation 3.",
        "Worship of the ancient Phrygian god Men persisted in Laodicea, and the medical school that developed there was connected with the temple of Men. Its medical tradition was influenced by teachings derived from the experiments and theories of Herophilos of Chalcedon, the fourth- and third-century B.C. physician who conducted anatomical and dissection experiments on hundreds of living prisoners in his efforts to advance medical knowledge. The medical tradition associated with Laodicea consequently possessed considerable knowledge of human anatomy, including the eye.",
        "The medical school became known throughout the Roman Empire and was particularly famous for ophthalmology. Among the treatments associated with this medical tradition was an eye preparation mentioned in several ancient sources. In the medical writings of the second-century A.D. physician Galen of Pergamon, an eye medicine was described as being made from a Phrygian stone, probably crushed into a powder or prepared as a form of clay. The word used by John for the eye “salve” in connection with Laodicea is the same word found in Galen and other medical writings of antiquity.",
        "Laodicea was also well known for its textile industry, particularly its wool. Archaeological evidence for this industry includes buildings used in the dyeing of wool, together with inscriptions referring to those involved in textile production. One inscription discovered at the north theatre identified traders and craftsmen, including an organization called “The Most August Guild of the Wool Washers.” The black wool and dyed wool for which Laodicea was famous provide the historical setting for the contrasting reference in Revelation to white garments.",
        "In the letter to Laodicea, the people are described as wretched, miserable, poor, blind, and naked and are advised to obtain gold in order to become rich, white garments with which to clothe themselves, and eye salve with which to anoint their eyes (Revelation 3:17–18). The criticism and counsel therefore employ imagery connected with activities and products for which Laodicea was known: trade, banking, medicine, and textiles.",
        "The church at Laodicea is also described as being neither hot nor cold, but lukewarm (Revelation 3:15–16). This language corresponded with the water conditions of Laodicea and those of the neighbouring cities of Hierapolis and Colossae. Hierapolis possessed hot springs, while Colossae had access to cold mountain water. Laodicea had neither a hot spring nor a cold mountain-water source and instead depended upon water transported by aqueduct from springs approximately eight kilometres away.",
        "The water was carried through a double pressurized pipeline and contained a high concentration of minerals. The accumulation of these minerals was sufficiently serious for Roman engineers to design removable caps in the aqueduct pipes so that mineral deposits could be cleared from the system, as discussed by John McRay in Archaeology and the New Testament. By the time the water reached Laodicea, it was lukewarm and heavily mineralized, probably making it unpleasant to drink.",
        "Despite these characteristics, the water supply was highly valued. Anyone who attempted to divert the water or use it for agricultural purposes could be fined. Damage to a water pipe could result in a fine of 5,000 denarii, an amount close to a year’s wages for entry-level agricultural workers, scribes, and teachers. City officials who permitted the unauthorized free use of the water could be subjected to still greater fines.",
        "Archaeological excavations have also found evidence that houses were used as meeting places by Christians during the Roman period. This corresponds with early Christian writings and, more specifically, with the reference to the church at Laodicea meeting in the house of Nympha or Nymphas.",
        "By the time John wrote Revelation, the imperial cult had been present in Laodicea for at least ten years. The imperial cult and a temple to the emperor had been established there during the reign of Domitian, beginning around A.D. 81.",
        "The Book of Revelation was written during the reign of the Roman emperor Domitian, who ruled from A.D. 81 to 96. Domitian was notorious for declaring himself a god while still alive. This offended Christians, Jews, and members of the Roman Senate. Other Roman emperors had generally been deified only after death.",
        "Those who refused to participate in the imperial cult, which involved the worship of emperors and their dynastic families, faced persecution under Domitian. Jews throughout the cities of the Mediterranean world, as monotheists, were exempt from the requirements of emperor worship as part of the Pax Romana. While Christianity continued to be regarded as a sect within Judaism, Christians in these cities likewise benefited from this exemption.",
        "The early Christian church was composed almost entirely of Jews. As increasing numbers of Gentiles converted to Christianity, however, the proportion of Jewish believers within Christianity declined. As Christianity became increasingly distinguished from Judaism, Christians lost the special status that had permitted them to refrain from emperor worship.",
        "The Christians of Laodicea were affected by Domitian’s decrees, and the resulting pressures extended to their ability to participate in economic activity. Revelation 13 describes the inability to buy or sell without the mark of the beast. For wealthy Christians in Laodicea, the pressure to maintain their economic position was particularly significant because so much of the city’s prosperity depended upon trade.",
        "Christian merchants therefore faced the question of whether they would cooperate with the imperial cult and maintain their trade associations or reject Domitian and reaffirm their faith in Christ. Many Laodicean Christians compromised their faith in response to these pressures. Their response forms the historical setting presented for the description of the church as “lukewarm” and for the warning, “I will spit you out of my mouth” (Revelation 3:16).",
        "The response of the Christians at Laodicea differed from that attributed to some other Christian communities in Revelation. The Christians at Smyrna, for example, are commended for maintaining their faith despite severe difficulties associated with their refusal to participate in the imperial cult. This refusal resulted in affliction and poverty, yet they are commended for their faithfulness in Revelation 2:9.",
        "Laodicea’s considerable economic resources are also illustrated by its response to natural disaster. A massive earthquake struck the city in A.D. 60, probably shortly before Paul wrote to the Colossians and instructed that his letter be shared with Laodicea. The wealth of the city enabled its inhabitants to rebuild without the usual financial assistance from Rome.",
        "Laodicea continued to exist into the Byzantine period. The city was eventually abandoned around the reign of Emperor Phocas, approximately A.D. 610, following another devastating earthquake.",
      ],
    },
  ],
};
